name: Add contributors
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.CONTRIBUTORS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install all-contributors-cli
        run: npm install -g all-contributors-cli

      - name: Generate contributors
        run: |
          all-contributors generate
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "docs: update contributors" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.CONTRIBUTORS_TOKEN }}
