name: Semantic Release on Merge
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Attempt Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v6
        with:
          semantic_version: 25.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
