name: Test Project Build
on:
  pull_request:
    types: [opened, reopened]
jobs:
  build:
    name: Test Project Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
