name: Test Project Build
on:
  pull_request:
    types: [opened, reopened]
jobs:
  build:
    name: Test Project Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add remote SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DRUPAL_ORG_SSH_KEY }}
          config: ${{ secrets.SSH_CONFIG }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Run project build
        run: |
          npm install
